/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e9e8e4",
        "on-primary": "#ffffff",
        "surface-variant": "#e3e2df",
        "primary": "#8f482f",
        "secondary-fixed-dim": "#cac6c2",
        "primary-fixed": "#ffdbd0",
        "surface-container-highest": "#e3e2df",
        "primary-container": "#ad5f45",
        "on-secondary-fixed": "#1c1b19",
        "tertiary-container": "#1d8372",
        "on-tertiary-fixed-variant": "#005045",
        "surface-container-low": "#f4f4f0",
        "on-background": "#1b1c1a",
        "on-tertiary-fixed": "#00201b",
        "surface-container": "#efeeea",
        "on-primary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb59d",
        "on-primary-fixed-variant": "#75331c",
        "muted": "#6c6a64",
        "border-hairline": "#e6dfd8",
        "canvas": "#faf9f5",
        "ink": "#141413",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#484644",
        "on-secondary-container": "#666461",
        "tertiary-fixed-dim": "#7cd7c4",
        "outline-variant": "#dac1ba",
        "surface-dim": "#dbdad6",
        "surface-card": "#efe9de",
        "tertiary": "#00685a",
        "background": "#faf9f5",
        "inverse-primary": "#ffb59d",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#390c00",
        "tertiary-fixed": "#98f3e0",
        "accent-amber": "#e8a55a",
        "outline": "#87736d",
        "on-tertiary-container": "#f4fffa",
        "secondary": "#605e5b",
        "secondary-container": "#e6e2de",
        "error": "#ba1a1a",
        "secondary-fixed": "#e6e2de",
        "surface-tint": "#924a31",
        "inverse-on-surface": "#f2f1ed",
        "surface-bright": "#faf9f5",
        "surface-dark": "#181715",
        "inverse-surface": "#2f312e",
        "on-surface-variant": "#54433e",
        "on-surface": "#1b1c1a",
        "surface": "#faf9f5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-padding": "32px",
        "gutter": "16px",
        "unit": "4px",
        "internal-gap": "12px",
        "section-v-rhythm": "96px",
        "margin-page": "48px"
      },
      fontFamily: {
        "headline-md": ["Newsreader", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-xl": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.15", letterSpacing: "-0.5px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.4", letterSpacing: "1.5px", fontWeight: "500" }],
        "title-lg": ["22px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-1px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
        "headline-xl": ["64px", { lineHeight: "1.05", letterSpacing: "-1.5px", fontWeight: "400" }],
        "headline-lg-mobile": ["36px", { lineHeight: "1.1", letterSpacing: "-0.5px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.55", letterSpacing: "0", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
